FILES_DATA_PATH = "/home/tausiaj/Documents/cambium-homework/streamlit/data"
# replace_to_docker = "/app/data"
# replace_to_local_path_example = "/home/tausiaj/Documents/cambium-homework/streamlit/data"
STATIC_FILES_PATH = "/home/tausiaj/Documents/cambium-homework/streamlit/cambiame-app/tmp"
# replace_to_docker = "/app/tmp"
# replace_to_local_path_example = "/home/tausiaj/Documents/cambium-homework/streamlit/cambiame-app/tmp"
EARTHENGINE_PROJECT = "ee-jtausiahoyal"
